fraud_history/Fscheck/urls.py
from argparse import Namespace
from django.urls import URLPattern
from . import views
from django.urls import path
from django.conf.urls import handler404


urlpatterns = [
    path('', views.index, name='index'),
]

handler404 = 'Fscheck.views.error_404_view'

fraud_history/fraud_history/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include(('Fscheck.urls', 'Fscheck'), namespace='Fscheck')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

fraud_history/Fscheck/models.py
from pyexpat import model
from statistics import mode
from django.db import models

class Fraud(models.Model):
    msisdn = models.CharField(max_length=12)
    fraud_description = models.TextField()
    still_ongoing = models.BooleanField()

    def __str__(self):
        return self.msisdn
        

class QueryLog(models.Model):
    username = models.EmailField()
    msisdn = models.CharField(max_length=12)
    query_date = models.DateTimeField("date queried")

    def __str__(self):
        return self.username

fraud_history/Fscheck/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Fraud, QueryLog
from datetime import datetime
# Create your views here.
def index(request):
    queries = QueryLog.objects.order_by('query_date')[:100]
    if request.method == "POST":
        msisdn = request.POST['msisdn']
        if msisdn.startswith("98"):
            msisdn = msisdn[2:]
        elif msisdn.startswith("0"):
            msisdn = msisdn[1:]
        QueryLog(username="test", msisdn=msisdn, query_date=datetime.now()).save()
        try:
            result = Fraud.objects.get(msisdn=msisdn)
        except Fraud.DoesNotExist:
            return render(request, 
                'fscheck/index.html', 
                {
                    'searched_msisdn': msisdn,
                    'queries' : queries, 
                    'result' : "No Fraud History."
                })
        return render(request, 
            'fscheck/index.html', 
            {
                'searched_msisdn': msisdn,
                'queries' : queries, 
                'result' : result.fraud_description
            })
    return render(request, 'fscheck/index.html', {
                                    'searched_msisdn': '9336661122',
                                    'queries' : queries,
                                    'result' : "Search Your MSISDN"})


def error_404_view(request, exception):
       
    # we add the path to the the 404.html file
    # here. The name of our HTML file is 404.html
    return render(request, '404.html')

fraud_history/Fscheck/templates/fscheck/index.html
{% extends 'global/base.html' %}

{% block content %}


<div class="row">
    <div class="p-4 bd-highlight">
      <div class="row">
        <div class="col-4 col-sm-4 p-2 bd-highlight" >
            <div class="row p-2 bd-highlight">
                <form action="{% url 'Fscheck:index' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" name="msisdn" id="msisdn" class="form-control" placeholder="{{searched_msisdn}}" aria-label="" aria-describedby="basic-addon1">
                        <div class="input-group-append">
                            <input class="btn btn-success" type="submit" value="Search">
                            <!-- <button class="btn btn-success" type="button">Search</button> -->
                        </div>
                    </div>
                </form>               
            </div>
            <div class="row p-2 bd-highlight">
                <p class="font-weight-bold">{{ result }}</p>
            </div>
        </div>
        <div class="col-8 col-sm-8 " >
          <div class="row p-2 bd-highlight">
            <table class="table table-sm">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>MSISDN</th>
                    <th>Date</th>
                  </tr>
                </thead>
                <tbody>
                    {% for el in queries %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{el.msisdn}}</td>
                            <td>{{el.query_date}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>

          </div>
        </div>
      </div>
    </div>
</div>

{% endblock %}

fraud_history/Fscheck/templates/global/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>SIM Fraud History Check</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'Fscheck/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link  rel="stylesheet" type="text/css" href="{% static 'Fscheck/css/styles.css' %}" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#">SIM Fraud history check</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <!-- <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Home</a></li> -->
                        <!-- <li class="nav-item"><a class="nav-link" href="#">Logout</a></li> -->
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'Fscheck/js/scripts.js' %}"></script>
    </body>
</html>